export default [
  {
    key: 'title',
    sortable: true,
    label: 'Наименование',
    thClass: 'text-center',
    thStyle: {width: "25%"},
  },
  {
    key: 'content',
    sortable: true,
    label: 'Контент',
    thClass: 'text-center',
    thStyle: {width: "20%"},
  },
  {
    key: 'reminder_title',
    sortable: true,
    label: 'Напоминание',
    thClass: 'text-center',
  },
  {
    key: 'user',
    sortable: false,
    label: 'Пользователь',
    thClass: 'text-center',
    tdClass: 'text-center',
  },
  {
    key: 'initiator_user',
    sortable: false,
    label: 'Пользователь, вызвавший получение уведомления',
    thClass: 'text-center',
    tdClass: 'text-center',
  },
  {
    key: 'initiator_user',
    sortable: false,
    label: 'initiator_user',
    thClass: 'text-center',
    tdClass: 'text-center',
  },
  {
    key: 'read_at',
    label: 'Дата прочтения',
    sortable: true,
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: {width: "150px"},
  },
  {
    key: 'completed_at',
    label: 'Дата выполнения',
    sortable: true,
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: {width: "150px"},
  },
  {
    key: 'expires_at',
    label: 'Когда истекает',
    sortable: true,
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: {width: "150px"},
  },
  {
    key: 'is_expired',
    sortable: false,
    label: 'Истек срок выполнения',
    thClass: 'text-center',
    tdClass: 'text-center',
  },
  {
    key: 'created_at',
    label: 'Дата создания',
    sortable: true,
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: {width: "150px"},
  },
  {
    key: 'actions',
    label: 'Действия',
    sortable: true,
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: {width: "120px"},
  },
]
