export default [
  {
    key: 'title',
    sortable: true,
    label: 'Наименование',
    thClass: 'text-center',
    thStyle: { width: '200px' },
  },
  {
    key: 'content',
    sortable: true,
    label: 'Контент',
    thClass: 'text-center',
    thStyle: { width: '40%' },
  },
  {
    key: 'reminder_title',
    sortable: true,
    label: 'Напоминание',
    thClass: 'text-center',
    thStyle: { width: '150px' },
  },
  {
    key: 'user',
    sortable: false,
    label: 'Получатель',
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: { width: '150px' },
  },
  {
    key: 'initiator_user',
    sortable: false,
    label: 'Инициатор',
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: { width: '150px' },
  },
  {
    key: 'read_at',
    label: 'Дата прочтения',
    sortable: true,
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: { width: '150px' },
  },
  {
    key: 'completed_at',
    label: 'Дата выполнения',
    sortable: true,
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: { width: '150px' },
  },
  {
    key: 'expires_at',
    label: 'Когда истекает',
    sortable: true,
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: { width: '150px' },
  },
  {
    key: 'created_at',
    label: 'Дата создания',
    sortable: true,
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: { width: '150px' },
  },
  {
    key: 'actions',
    label: 'Действия',
    sortable: true,
    thClass: 'text-center',
    tdClass: 'text-center',
    thStyle: { width: '120px' },
  },
]
