<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class Req extends Model
{
    use SoftDeletes;

    public $fillable
        = [
            'hash_id',
            'name',
            'stamp_id',
            'inn',
            'bik',
            'kc',
            'rc',
            'banks',
            'director',
            'director_fio',
            'signature',
            'seal',
            'deleted_id',
            'deleted_at',
            'auto_created'
        ];

    public function delete()
    {
        $this->deleted_id = user()->id;
        $this->save();

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function deleted_user()
    {
        return $this->belongsTo(User::class, 'deleted_id', 'id')
                    ->withDefault();
    }
    public function getName($id)
    {
        $reqs = Req::find($id);

        if ( !$reqs) {
            $reqs = '';
        } else {
            $reqs = $reqs['name'];
        }

        return $reqs;
    }

    public static function getAll()
    {
        return self::all();
    }

    public function stamp(): BelongsTo
    {
        return $this->belongsTo(Stamp::class);
    }
}
