<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Settings extends Model
{
    use \Illuminate\Database\Eloquent\SoftDeletes;

    public $fillable
        = [
            'id',
            'logo',

            'sms_api_key',
            'sms_text_driver',
            'sms_text_car',
            'sms_text_phone',
            'sms_text_default',
            'deleted_id'
        ];

    public function delete()
    {
        $this->deleted_id = user()->id;
        $this->save();

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function deleted_user()
    {
        return $this->belongsTo(User::class, 'deleted_id', 'id')
                    ->withDefault();
    }

    public static function setting($setting)
    {
        $data = self::first();

        if (isset($data->$setting)) {
            return $data->$setting;
        }

        return '';
    }

    public static function getAll()
    {
        return self::all();
    }
}
