<?php

namespace App\Dtos\Contracts;

use ReflectionProperty;
use Spatie\DataTransferObject\FieldValidator as BaseFieldValidator;

class FieldValidator extends BaseFieldValidator
{

    /**
     * @param  \ReflectionProperty  $property
     * @return \Spatie\DataTransferObject\FieldValidator
     */
    public static function fromReflection(ReflectionProperty $property): BaseFieldValidator
    {
        //pass
        return BaseFieldValidator::fromReflection($property); // TODO: Change the autogenerated stub
    }

}